### ISSUE TITLE
404 sur lien "Autheur·e" 

### ISSUE THREAD

**Issue by chriscamicas** [Libelilou/libelilou.github.io#4]
Le lien 'Autheur·e' en bas des posts (includes author.html) renvoie vers un 404 sur GooglePlus car le site.gplus_username n'est pas renseigné.
Peut-être juste supprimer le <a> si tu ne veux pas t'embêter avec une page de profil/autheur.
```
<a itemprop="name" href="https://plus.google.com/+{{site.gplus_username}}/posts">{{site.username}}</a>```

et merci à PrincesseRH pour les articles ;)

**Comment by borisschapira** [comment]
Fixed by 64c9ef4ddea4f9436d368bb011dff0b957ac0970, merci @chriscamicas !
